### ISSUE TITLE
Wish to support gzip upload option

### ISSUE THREAD

**Issue by jspark-gigworks** [ChenglongMa/skipper-gcstorage#1]
Hi.

According to [Gooble Cloud Storage API document](https://googleapis.dev/nodejs/storage/5.6.0/global.html#CreateWriteStreamOptions), `gzip` option is supported.
I hope that skipper-gcstorage should support it.

Coud you please implement it?

**Comment by ChenglongMa** [comment]
Hi @jspark-gigworks,
Thanks for your recommendation. I will try to implement it 👍

**Comment by ChenglongMa** [comment]
Hi @jspark-gigworks,
I have published [the new version](https://www.npmjs.com/package/skipper-gcstorage) which has supported all options listed in the [Google Cloud Storage API document](https://googleapis.dev/nodejs/storage/5.6.0/global.html#CreateWriteStreamOptions) and fixed the `writefile` event issue.

Thanks again for your comments! I will close these two issues. 🤝
