### ISSUE TITLE
Keep file names

### ISSUE THREAD

**Issue by jungalwala** [ChenglongMa/skipper-gcstorage#9]
Is there a way to keep the original filenames of the uploaded files?  Right now it is forcing a UUID.

**Comment by ChenglongMa** [comment]
Hi @jungalwala, sorry for the late reply. I was busy with other projects. I will fix it in the following days. Thanks!

**Comment by ChenglongMa** [comment]
Hi @jungalwala, I've released the new version which can keep the original filename or set it to a new customized filename.

Thanks!
